name: manually-trigger

on:
  workflow_dispatch:
    inputs:
      email:
        description: Your Email
        required: true
      startDate:
        description: Start date
        default: "2021-01-01"
        required: true
      count:
        description: Count? (commit count per day)
        default: "5"
        required: true
      useDynamic:
        description: Use dynamic? (commit dynamic times between 1~count per day)
        default: "true"
        required: true
      workdayOnly:
        description: Workday only? (only commit MON~FRI)
        default: "false"
        required: true

jobs:
  autoCommits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node v16
        uses: actions/setup-node@v1
        with:
          node-version: '16.0'
      - run: |
          git config --local user.email "${{ github.event.inputs.email }}"
          git config --local user.name ${{ github.actor }}
          git remote set-url origin https://github.com/${{ github.repository }}
      - run: yarn install
      - run: |
          yarn start \
          --startDate=${{ github.event.inputs.startDate }} \
          --count=${{ github.event.inputs.count }} \
          --useDynamic=${{ github.event.inputs.useDynamic }} \
          --workdayOnly=${{ github.event.inputs.workdayOnly }}
